import {
  CardRarity,
  HearthstonCardType,
  HearthstoneClass,
  RatedCard,
} from 'src/app/shared/models/hs-card';

// Those mocks are used so we know how many skeletons need to be rendered

export const RATED_CARDS_MOCK: RatedCard[] = [
  {
    description: '',
    expansion: '',
    hsClass: HearthstoneClass.DEATH_KNIGHT,
    imageURL: '',
    mana: 0,
    name: '',
    rarity: CardRarity.BASIC,
    rating: 1,
    type: HearthstonCardType.HERO,
  },
  {
    description: '',
    expansion: '',
    hsClass: HearthstoneClass.DEATH_KNIGHT,
    imageURL: '',
    mana: 0,
    name: '',
    rarity: CardRarity.BASIC,
    rating: 1,
    type: HearthstonCardType.HERO,
  },
  {
    description: '',
    expansion: '',
    hsClass: HearthstoneClass.DEATH_KNIGHT,
    imageURL: '',
    mana: 0,
    name: '',
    rarity: CardRarity.BASIC,
    rating: 1,
    type: HearthstonCardType.HERO,
  },
  {
    description: '',
    expansion: '',
    hsClass: HearthstoneClass.DEATH_KNIGHT,
    imageURL: '',
    mana: 0,
    name: '',
    rarity: CardRarity.BASIC,
    rating: 1,
    type: HearthstonCardType.HERO,
  },
  {
    description: '',
    expansion: '',
    hsClass: HearthstoneClass.DEATH_KNIGHT,
    imageURL: '',
    mana: 0,
    name: '',
    rarity: CardRarity.BASIC,
    rating: 1,
    type: HearthstonCardType.HERO,
  },
  {
    description: '',
    expansion: '',
    hsClass: HearthstoneClass.DEATH_KNIGHT,
    imageURL: '',
    mana: 0,
    name: '',
    rarity: CardRarity.BASIC,
    rating: 1,
    type: HearthstonCardType.HERO,
  },
  {
    description: '',
    expansion: '',
    hsClass: HearthstoneClass.DEATH_KNIGHT,
    imageURL: '',
    mana: 0,
    name: '',
    rarity: CardRarity.BASIC,
    rating: 1,
    type: HearthstonCardType.HERO,
  },
  {
    description: '',
    expansion: '',
    hsClass: HearthstoneClass.DEATH_KNIGHT,
    imageURL: '',
    mana: 0,
    name: '',
    rarity: CardRarity.BASIC,
    rating: 1,
    type: HearthstonCardType.HERO,
  },
  {
    description: '',
    expansion: '',
    hsClass: HearthstoneClass.DEATH_KNIGHT,
    imageURL: '',
    mana: 0,
    name: '',
    rarity: CardRarity.BASIC,
    rating: 1,
    type: HearthstonCardType.HERO,
  },
  {
    description: '',
    expansion: '',
    hsClass: HearthstoneClass.DEATH_KNIGHT,
    imageURL: '',
    mana: 0,
    name: '',
    rarity: CardRarity.BASIC,
    rating: 1,
    type: HearthstonCardType.HERO,
  },
];
