name: 🛠️ Feature Request
description: Suggest an idea to help us improve HS Set Review
title: "[Feature]: "
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a feature request! Before you fill out this form, please [check if it's already been suggested](https://github.com/mateuscechetto/hearthstone-set-review-bot/labels/feature%20request).
  
  - type: textarea
    attributes:
      label: Description
      description: |
        A brief summary of the feature you'd like to see added and why.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: |
        Describe any alternatives you may have considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
